### ISSUE TITLE
Bee Mutation seem completely broken

### ISSUE THREAD

**Issue by EnderiumSmith** [thedarkcolour/ForestryCE#51] opened 2024-08-19 15:34 UTC
I got an endemic drone from a purebreed jungle bee, as well as a common from purebreed jungle and purebreed forest. I also got a cultivated from a purebreed common. Its also way harder than i remember to get common bees to mutate, i had like 6 apiaries of forest/meadow and barely got 1 to stay. I suspect something is inverted in the logic somewhere.

This was on 1.0.3 and i did notice something about in the other reports but it takes too long to test again.

**Comment by thedarkcolour** [comment] 2024-08-19 21:21
> I also got a cultivated from a purebreed common

This is a known bug where bee species can mutate with themselves. It has been fixed in a commit, but is not yet available in a CurseForge release.

> I got an endemic drone from

What is an endemic drone?

**Comment by thedarkcolour** [comment] 2024-08-19 21:45
Ah, you meant Edenic. That is part of the same breeding bug that causes the purebred mutating to common, which was fixed in [b089673657f80e393c15d15e5f2a03bd606b55d9](https://github.com/thedarkcolour/ForestryMC/commit/b089673657f80e393c15d15e5f2a03bd606b55d9).

**Closed as not planned by thedarkcolour** 2024-08-19 21:45 UTC
Labels: bug

**Comment by thedarkcolour** [comment] 2024-08-19 23:24
Duplicate of #49
